name: ceiba
description: Test for ceiba.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.0
  flutter_native_splash: ^2.3.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter_native_splash:
  fullscreen: true
  android: true
  ios: true
  color: "#303236"
  image: assets/splash768.png
  android_12:
    color: "#303236"
  android_gravity: fill_horizontal|fill_vertical
  ios_content_mode: scaleAspectFit

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 26


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
